### ISSUE TITLE
Parsing error: Cannot find module '@babel/preset-react'

### ISSUE THREAD

**Issue by Learning-X** [wesbos/eslint-config-wesbos#100]
Hi there -
It's been a while that I'm using wesbos awesome setup and when I create a fullstack project structure folder, I always get this error: Parsing error: Cannot find module '@babel/preset-react'.
- The module '@babel/preset-react' is indeed there under node_modules.
- Tried to npm install --save-dev @babel/preset-react 

I've noticed that it's only happening when I create this project structure: 

1. I create a projectx folder and add in it: projectx-frontend and it's working fine at this point.
2. I then add another folder in the main folder projectx: projectx-backend
3.  But if I have a main folder in vscode with the front and back files, I get this error...

-- projectx -> npm init -y and use npm i concurrently,  this create Cannot find module '@babel/preset-react'
          -- projectx-frontend -> npx install-peerdeps --dev eslint-config-wesbos WORKS FINE alone without main folder
          -- projectx-backend -> npx install-peerdeps --dev eslint-config-wesbos WORKS FINE alone without main folder

Anyone can help on this please? Thanks in advance.

![Screenshot 2021-10-31 at 10 44 01](https://user-images.githubusercontent.com/73561922/139577224-132a0526-84e6-4c9c-ac3d-988ea01b917d.png)

**Comment by danil0man** [comment]
I am getting the same error, does someone have a solution to this?

**Comment by wesbos** [comment]
Are you opening the folder that has the .eslint file in it? Or a parent folder? I know @Asjas was mentioning a few people having this on my tuts

**Comment by danil0man** [comment]
My file structure looks like this
![image](https://user-images.githubusercontent.com/72052103/141854760-5f655f15-b842-47ba-80a8-665c1e3b571b.png)

**Comment by wesbos** [comment]
You have opened a folder called "2. JS" and no the `beginner-javascript` folder. 

Close your editor and open the beginner-javascript folder as the root.

More info here: https://github.com/wesbos/Wes-Bos-Video-Notes/blob/master/BJS/5%20-%20Code%20Quality%20Tooling%20with%20Prettier%20and%20ESLint%20-%20375475807.md

**Comment by danil0man** [comment]
Yeah, that did it. Thx you wes bos, the fastest response ever. You are the man

**Comment by wesbos** [comment]
:D

**Comment by wesbos** [comment]
@Learning-X i assume this is your issue as well. Please re-open if its not

**Comment by legendkong** [comment]
> You have opened a folder called "2. JS" and no the `beginner-javascript` folder.
> 
> Close your editor and open the beginner-javascript folder as the root.
> 
> More info here: https://github.com/wesbos/Wes-Bos-Video-Notes/blob/master/BJS/5%20-%20Code%20Quality%20Tooling%20with%20Prettier%20and%20ESLint%20-%20375475807.md

Apologies for bringing up an old thread, but this was a godsend. Couldn't find any solution that worked online except this!

**Comment by pladaria** [comment]
You can open from the repo root without issues if you configure a `.vscode/settings.json` file with this contents:
```
{
    "eslint.workingDirectories": ["./path/to/my/project"]
}
```
