### ISSUE TITLE
Setting Up GitHub Actions

### ISSUE THREAD

**Issue by 7chris71000** [wesbos/eslint-config-wesbos#104]
Has anyone been able to successfully use this config in a GitHub action? I have been using No-Sweat™ Eslint and Prettier for a while now on my projects in VSCode and I would like to add an action to my repository that will run this linting/formatting setup on my whole project. I can't find any issues on this repository asking about using this in an action so hopefully this isn't a duplicate.

**Comment by wesbos** [comment]
You should be able to do it with something like this:

https://github.com/marketplace/actions/action-eslint

the important part here being `      - uses: sibiraj-s/action-eslint@v2`
