### ISSUE TITLE
WSL + Create React App result: ERR undefined

### ISSUE THREAD

**Issue by Dujota** [wesbos/eslint-config-wesbos#105]
just following the instructions on adding no sweat eslint to CRA, but it fails on install. 

couldnt find anything specific, but I think this may some issue with a dependency? 
reference: https://stackoverflow.com/questions/66967270/err-undefined-while-installing-airbnb-eslint

Has anyone encountered this issue? 

```
npx install-peerdeps --dev eslint-config-wesbos
install-peerdeps v3.0.3
Installing peerdeps for eslint-config-wesbos@latest.
npm install eslint-config-wesbos@3.0.2 @babel/core@^7.16.0 @types/node@^16.11.12 
@typescript-eslint/eslint-plugin@^5.6.0 @typescript-eslint/parser@^5.6.0 eslint@^8.4.1 
eslint-config-airbnb@^19.0.2 eslint-config-airbnb-typescript@^16.1.0 eslint-config-prettier@^8.3.0 
eslint-plugin-html@^6.2.0 eslint-plugin-import@^2.25.3 eslint-plugin-jsx-a11y@^6.5.1 eslint-plugin-prettier@^4.0.0 
eslint-plugin-react@^7.27.1 eslint-plugin-react-hooks@^4.3.0 prettier@^2.5.1 
typescript@^4.5.2 @babel/eslint-parser@^7.16.3 @babel/preset-react@^7.16.0 --save-dev

ERR undefined
```

**Comment by Asjas** [comment]
@Dujota `ERR undefined` is a common npm installation error if the version of Node is too new. Can you tell us which version of Node.js you are using? Node 14 and Node 16 should work and you can use either of them 🙂

**Comment by Dujota** [comment]
@Asjas i am using v16.14.0 (lts)

**Comment by Asjas** [comment]
What happens if you try Node 14?

**Comment by 7chris71000** [comment]
@Dujota Was having this same issue on a new project. I had no problems after switching to v14.18.1. Thanks @Asjas
