### ISSUE TITLE
Global npx install fails

### ISSUE THREAD

**Issue by cycle4passion** [wesbos/eslint-config-wesbos#11]
![Screen Shot 2019-03-09 at 10 15 29 AM](https://user-images.githubusercontent.com/6192217/54073375-5c9d2780-4254-11e9-8e15-13e04bc4c547.png)

also tried and failed with reset via 

```javascript
npm remove --global eslint-config-wesbos babel-eslint eslint eslint-config-prettier eslint-config-airbnb eslint-plugin-html eslint-plugin-prettier eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react prettier
```

**Comment by cycle4passion** [comment]
Solved my own issue.
I did not realize install-peerdeps was a npm package, not just a npx flag.

installed the package first, and that did the trick.

```javascript
npm install -g install-peerdeps
```

**Comment by wesbos** [comment]
hmm this shouldn't be needed. what version of npm are you on?

**Comment by cycle4passion** [comment]
6.9.0 as shown

**Comment by wesbos** [comment]
Oh haha! Thanks
