### ISSUE TITLE
Command returns ERR undefined with new updates dependencies

### ISSUE THREAD

**Issue by jaspervermeulen** [wesbos/eslint-config-wesbos#110]
Started a new project and couldn't install my go to linter 😄, had to switch back dependencies, couldn't exactly figure out which dependency was the cause. 

Doesn't work with:
```
    "autoprefixer": "^10.4.4",
    "eslint": "8.12.0",
    "eslint-config-next": "12.1.2",
    "postcss": "^8.4.12",
    "tailwindcss": "^3.0.23"
```

Works with: 
```
    "autoprefixer": "^10.4.2",
    "eslint": "8.12.0",
    "eslint-config-next": "12.1.0",
    "postcss": "^8.4.7",
    "tailwindcss": "^3.0.23"
```

Received error:
```
ERR undefined
```

**Comment by wesbos** [comment]
the only dep I use in your list is eslint, and that didn't change on you end. Is there more info on the error?

**Comment by jaspervermeulen** [comment]
Weird no, the error in the terminal just said ERR undefined.. couldn't figure it out so i just used the info from an older project and only when changing these it worked

**Comment by jaspervermeulen** [comment]
It will probably be something on my end i've done wrong, was confused and couldn't find a way for it to work so wanted to check if it could be something because of the updates! Will close the issue 😄 (huge fan btw have multiple courses and love the stickers 😆)
