### ISSUE TITLE
Custom Prettier options first need to be copied to avoid conflicts

### ISSUE THREAD

**Issue by spacecakes** [wesbos/eslint-config-wesbos#13]
Just a tip that maybe should be mentioned in the readme: if one wants to customize Prettier's behavior, you first need to copy the supplied Prettier rules and go from there:

```
 "prettier/prettier": [
      "error",
      {
        "trailingComma": "es5",
        "singleQuote": true,
        "printWidth": 80,
      }
    ],
```

or at the very least copy `"singleQuote": true` since any change to the `prettier/prettier` object will overwrite the initial settings and cause conflicts with eslint. Prettier's default is double quotes and so they'll battle each other to death over quotations if Prettier isn't told to change its mind.

Thanks for this by the way. Has never been easier.

**Comment by wesbos** [comment]
hmm - I thought they would overlap each other. Thanks for the issue - will update the docs

**Comment by wesbos** [comment]
fixed https://github.com/wesbos/eslint-config-wesbos/commit/e405fe972519f0e57fce9c38865f91a9e73201e3
