### ISSUE TITLE
es lint command not found

### ISSUE THREAD

**Issue by jana-personal** [wesbos/eslint-config-wesbos#138]
Since we don't use config globally. Am getting error eslint command not found.

1. Followed this steps https://github.com/wesbos/eslint-config-wesbos#project-install
2. My package.json 
```
{
  "name": "beginner-javascript",
  "version": "1.0.0",
  "description": "![](https://res.cloudinary.com/wesbos/image/upload/v1574876851/BJS/BJS-Social-Share.png)",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "eslint-config-wesbos": "^4.0.1"
  },
  "eslintConfig": {
    "extends": ["wesbos"]
  }
}

```
3. Error when am trying to run `npm run lint`
```
❯ npm run lint                                                                                                                                                   

> beginner-javascript@1.0.0 lint
> eslint .

sh: eslint: command not found
```
4. In VS code console got this error
```
Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': connect EBADF.
```

**Comment by jana-personal** [comment]
@wesbos need help. Spent hours of debugging still no luck

**Comment by Asjas** [comment]
Install eslint and prettier and retry?
npm i eslint@8.0.0 prettier@2.7.1

**Comment by Asjas** [comment]
Install `eslint` and `prettier` and retry?
```sh
npm i eslint@8.0.0 prettier@2.7.1
```

**Comment by jana-personal** [comment]
> Install `eslint` and `prettier` and retry?
> 
> ```shell
> npm i eslint@8.0.0 prettier@2.7.1
> ```

Thanks @Asjas . But now am getting this error

```
❯ npm run lint                                                                                                                                                  

> beginner-javascript@1.0.0 lint
> eslint .

Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

Oops! Something went wrong! :(

ESLint: 8.0.0

TypeError: prettier.resolveConfig is not a function
    at /Users/xx/xx/beginner-javascript/node_modules/eslint-plugin-prettier/worker.js:38:24
```

**Comment by Asjas** [comment]
Do not install Prettier v3.

**Comment by jana-personal** [comment]
> Do not install Prettier v3.

Installed v2 as you mentioned 

❯ npm ls                                                                                                                                                       
beginner-javascript@1.0.0 /Users/xx/xx/beginner-javascript
├── eslint-config-wesbos@4.0.1
├── eslint-plugin-react@7.33.2
├── eslint@8.0.0
└── prettier@2.7.1

**Comment by jana-personal** [comment]
> Do not install Prettier v3.

Installed v2 as you mentioned, still no same reason

❯ npm ls
beginner-javascript@1.0.0 /Users/xx/xx/beginner-javascript
├── eslint-config-wesbos@4.0.1
├── eslint-plugin-react@7.33.2
├── eslint@8.0.0
└── prettier@2.7.1

**Comment by jana-personal** [comment]
@wesbos @Asjas Any clue?

**Comment by jana-personal** [comment]
Solved

**Comment by ampcpmgp** [comment]
May I ask how it was resolved?

**Comment by maulerjan** [comment]
No :D
