### ISSUE TITLE
VS Code - Windows - cannot find module eslint-config-wesbos

### ISSUE THREAD

**Issue by JohnMilazzo** [wesbos/eslint-config-wesbos#2]
Getting this error:

[Info  - 4:27:39 PM] ESLint server stopped.
[Info  - 4:27:40 PM] ESLint server running in node v10.2.0
[Info  - 4:27:40 PM] ESLint server is running.
[Info  - 4:27:43 PM] ESLint library loaded from: c:\dev\projectname\node_modules\eslint\lib\api.js
[Error - 4:27:43 PM] Cannot find module 'eslint-config-wesbos' Referenced from: C:\Users\username\\.eslintrc

Does it have something to do with ESLint attempting to reference my project's local node_modules even though I installed this globally?   I have no dev dependencies in this particular package.json.

**Comment by denvercoder** [comment]
Did you npm install that package?

**Comment by phifa** [comment]
Yeah I am running into this as well. Should I install global or local? 🧐

**Comment by wesbos** [comment]
Yeah, if you have eslint installed locally for a project then you need to install this locally and have a local eslint file.

Could you try the local instructions and see if that works?

**Comment by JohnMilazzo** [comment]
That did the trick.  One of the Gatsby plugins seems to have added eslint as a local dependency.

**Comment by wesbos** [comment]
good to know - I think ill put the local install instructions up first

**Comment by wesbos** [comment]
okay I've fixed the instructions to favour local install 👌
