### ISSUE TITLE
`react/jsx-filename-extension` rule is being overridden

### ISSUE THREAD

**Issue by Hillsie** [wesbos/eslint-config-wesbos#22]
Hopefully, this will help someone else.
I'm building a gatsby project and have found that the rule below is not being applied. 

```"react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],```

 Looks like the Airbnb rules under ```node_modules``` takes precedence. 

Adding the rule to the ```node_modules/eslint-config-airbnb/rules/react-a11y.js``` file seems to have resolved the issue. Happy Days 🙃

version information:
```react@16.8.6
node v11.4.0
gatsby@2.3.25
eslint@5.16.0

**Comment by abhijithvijayan** [comment]
@Hillsie Adding the rules directly to `node_modules` is never a good idea.

One `npm i` can override that.

**Comment by Hillsie** [comment]
> @Hillsie Adding the rules directly to `node_modules` is never a good idea.
> 
> One `npm i` can override that.

Thanks, yes, since the comment I also realised that.
