### ISSUE TITLE
WSL 

### ISSUE THREAD

**Issue by deanhtid** [wesbos/eslint-config-wesbos#23]
Anyone got this working on WSL. can't for the life of me get it working. Followed Wes's steps but not for windows as I want it working within Linux

[Info  - 16:00:26] ESLint server stopped.
[Info  - 16:00:27] ESLint server running in node v10.2.0
[Info  - 16:00:27] ESLint server is running.
[Info  - 16:00:28] 

Not sure why it says node version 10 when I have 12 installed

Any help would be great

**Comment by petercr** [comment]
Yeah actually I have it running on WSL Debian with no problems, but I have a personal updated version I made myself. 
Check which version of Node you have installed on your WSL distro. You need a separate installation on each WSL distro of Node JS and Yarn if you plan on using that as well.
