### ISSUE TITLE
Add .eslintignore info to readme

### ISSUE THREAD

**Issue by kallebornemark** [wesbos/eslint-config-wesbos#24]
I spent a lot of time trying to figure out why my VS Code refactoring and overall IntelliSense was so slow with this setup. I finally found that I had to add `node_modules` to `.eslintignore`.

Even though it's not a problem specific to this project, perhaps it could be added to the readme?

**Comment by wesbos** [comment]
Hey! It should do this by default. 

from https://eslint.org/docs/user-guide/configuring

> In addition to any patterns in a .eslintignore file, ESLint always ignores files in /node_modules/* and /bower_components/*.
