### ISSUE TITLE
breaking changes in eslint-plugin-html

### ISSUE THREAD

**Issue by sriramr98** [wesbos/eslint-config-wesbos#28]
There is a bug in the current version of eslint-plugin-html included in this config. 
This bug doesn't detect the presence of eslint and breaks.

Solution : Upgrade eslint version to 6.1.0 and upgrade eslint-plugin-html to 6.0.0

**Comment by fabianstarke** [comment]
@sriramr98 Thank for this it worked for me !

**Comment by abhijithvijayan** [comment]
Fixed in the latest release of https://github.com/onepassapp/eslint-config-onepass

**Comment by jmannfeld** [comment]
Thanks, worked for me too!

**Comment by fam246** [comment]
The solution below worked for me

https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-512252381

**Comment by wesbos** [comment]
Fixed!
