### ISSUE TITLE
npx install-peerdeps hangs

### ISSUE THREAD

**Issue by dipetersen** [wesbos/eslint-config-wesbos#3]
When I run the command npx install-peerdeps --global eslint-config-wesbox
I first get an error that the "path" argument must be of type string
then it says it installed npx
then it launches cli.js and then hangs.

I've let it wait for 20+ min. Nothing.
I ran the uninstall command both globally and local, deleted the node_modules directory and tried to re-run the npx command.  same problem.

**Comment by wesbos** [comment]
Hmm - I think it's because wesbo**s** no wesbo**x*

**Comment by dipetersen** [comment]
Sorry - that's a typo in my issue above.  I did type the command correctly in my terminal
![image](https://user-images.githubusercontent.com/2683871/53507107-e262eb00-3a7c-11e9-8b4c-da2bd644aea3.png)

**Comment by wesbos** [comment]
seems this is related to npx and not this tool: 

https://github.com/zkat/npx/issues/148
