### ISSUE TITLE
Using together with typescript?

### ISSUE THREAD

**Issue by kiprasmel** [wesbos/eslint-config-wesbos#33]
Hello,

I'm using typescript quite often & would love to use this same config for typescript projects aswell.

I thought maybe someone has already encountered & solved this use case & could share the solution - thanks!

**Comment by sarpik** [comment]
So I managed to get typescript working with eslint myself!

I'll document precisely what you need to do to get it working yourself if you're using `eslint-config-wesbos`,
but in the meantime, you can explore [the different between this repo & mine](https://github.com/wesbos/eslint-config-wesbos/compare/master...sarpik:master) (click `Files changed`) - the most important is obviously the `.eslintrc.js`

https://github.com/typescript-eslint/typescript-eslint
& specifically https://github.com/typescript-eslint/typescript-eslint#how-do-i-configure-my-project-to-use-typescript-eslint helped a lot!

**Comment by thousandknives** [comment]
I did not look into it but I just saw this package on npmjs.com that extends the eslint-config-wesbos and also has typescript support: https://www.npmjs.com/package/eslint-config-gristow

**Comment by sarpik** [comment]
@thousandknives Yeah that's cool.
Btw, mine's available @ https://www.npmjs.com/package/eslint-config-sarpik (https://github.com/sarpik/eslint-config-sarpik)

**Comment by abhijithvijayan** [comment]
https://www.npmjs.com/package/eslint-config-onepass with eslint 6 & typescript 3.7 support

**Comment by corysimmons** [comment]
@abhijithvijayan Nice work!

**Comment by abhijithvijayan** [comment]
@corysimmons Thanks. It l sort of a standalone pluggable fork.

**Comment by wesbos** [comment]
Thanks everyone -super helpful. I've begun work on typescript support for this package. 

You can check it out on this branch: https://github.com/wesbos/eslint-config-wesbos/tree/typescript

Still early WIP, so no docs but will update when its ready to try out

**Comment by wesbos** [comment]
https://github.com/wesbos/eslint-config-wesbos/issues/68

Beta is out. Closing this issue
