### ISSUE TITLE
dependency error:   "babel-eslint": "10.0.3"

### ISSUE THREAD

**Issue by nsilverio** [wesbos/eslint-config-wesbos#36]
Hello guys 
I tried all the above and it is still not working for me.  Does anyone have a solution to this issue?

Thanks

1. After updating `create-react-app`, 
2. Installed `npx install-peerdeps --dev eslint-config-wesbos`
3. Deleted `node_modules` & `package-lock.json`
4. Removed entry for `babel-eslint` from `package.json`
5. Created a `.eslintrc` file at the root
5. Ran `npm install`
6. Changed entry `eslintConfig` to `"extends": "wesbos"`
7. Voila, it works

Edit: See this https://github.com/wesbos/eslint-config-wesbos/issues/17#issuecomment-513640120

_Originally posted by @abhijithvijayan in https://github.com/wesbos/eslint-config-wesbos/issues/17#issuecomment-487132509_

**Comment by nsilverio** [comment]
Duplicated by mistake

**Comment by abhijithvijayan** [comment]
why not use

`npx install-peerdeps --dev eslint-config-onepass@latest` 

Which is my custom fork!
