### ISSUE TITLE
npm warn eslint-plugin-import

### ISSUE THREAD

**Issue by dpDesignz** [wesbos/eslint-config-wesbos#37]
I am trying to run the global install but I keep getting this warning

`npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint-plugin-import@^2.17.2 but none is installed. You must install peer dependencies yourself.`

I have tried installing it but I keep getting more error to follow. Is this something I need to be worried about or is it fine to ignore? I also can't seem to get my inline javascript to fix itself in html files. I'm not sure if this is related. Is there any way for this to work or am I misunderstanding what this does?

**Comment by andyboltondev** [comment]
I was also getting this warning when installing globally on my Windows 10 machine, however, it always seemed to work without any issues.

I am currently in the process on setting up WSL2 on my machine and I have not had this issue, so I believe it is related to Windows.

**Comment by wesbos** [comment]
keep me updated. Peer dependencies are weird..
