### ISSUE TITLE
Can no longer install it in expo project

### ISSUE THREAD

**Issue by yhenni1989** [wesbos/eslint-config-wesbos#38]
I used this plugin several times in my react native project. 

But today I tired to install it in a new project. I run in my root project
    `npx install-peerdeps --dev eslint-config-wesbos`

It seems as if you are using Yarn. Would you like to use Yarn for the installation? (y/n) y

Then nothing happens. My _**package.json**_ does not have the dependencies installed.

Does anyone have a similar issue?

**Comment by tvanantwerp** [comment]
I'm experiencing the same issue. Choosing `n` doesn't work either.

**Comment by AllanFerencz** [comment]
I had the same problem. It seems to be an issue with install-peerdeps. 

Try running `npx install-peerdeps --dev eslint-config-wesbos -Y`

Hopefully, that fixes the problem

**Comment by wesbos** [comment]
adding to docs, thanks!
