### ISSUE TITLE
Custom Prettier rules are not working.

### ISSUE THREAD

**Issue by felipeS** [wesbos/eslint-config-wesbos#4]
Apparently, it's only taking into account the Prettier default rules. I have the following rule in my `settings.json`: 
{
  "prettier.printWidth": 132,
}

But it's always cutting my lines at 80.

**Comment by wesbos** [comment]
Hmm - let me take a look into this. You are sure you don't have a prettier config file in your folder?

**Comment by felipeS** [comment]
I'm testing in a single file in a folder, there's no `.eslintrc` or `.prettierrc` file

**Comment by wesbos** [comment]
and was this with a global or local install?

**Comment by felipeS** [comment]
Global install

**Comment by NickyMeuleman** [comment]
The value set in `settings.json` probably only affects the VSCode prettier extensions.

https://github.com/prettier/eslint-plugin-prettier#options

**Comment by wesbos** [comment]
hmm I don't recall this being an issue for me and I've always used it this way. Will investigate :)

**Comment by wesbos** [comment]
Oh - just reading this again and I see the issue. 

I don't use the prettier vs code extension, and if you followed my steps, you will see that we turned it off. 

So, if you want to overwrite any settings that I have, you need to do so in your `.eslintrc`, and not in your VS Code settings file.  

It would then look like this:

```json
{
  "extends": [
    "wesbos"
  ],
  
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "printWidth": 135,
      }
    ]
  }
}
```

**Comment by wesbos** [comment]
Going to leave this open so I can document how to add custom eslint and prettier settings to overwrite any that my config sets

**Comment by felipeS** [comment]
I followed the steps and disabled the vs code extension, but I wasn't aware that I have to add the prettier rules to the `.eslintrc` file, didn't even know it was possible  😅It's working now, though.
Thanks!

**Comment by wesbos** [comment]
well im glad you logged this issue because that is exactly what I wanted to find out - little sticking points like this is what cause people to abandon tools like this. Glad we could get it figured out!

**Comment by JohnMilazzo** [comment]
Same here.  Through some trial and error I realized I could remove the settings from both VS Code and my project's .prettierrc file.   Having everything in one place (.eslintrc) is prettier nice!  ;)

**Comment by wesbos** [comment]
Okay ive documented this in the readme now. Opted against using a .prettierrc
