### ISSUE TITLE
create-react-app does NOT need ejecting

### ISSUE THREAD

**Issue by kiprasmel** [wesbos/eslint-config-wesbos#42]
You can use eslint with CRA without ejecting!

I've updated [my fork's installation steps for CRA](https://github.com/sarpik/eslint-config-sarpik#with-create-react-app) - you can take them & update yours too.

TL;DR:

1. Run `npx install-peerdeps eslint-config-sarpik --dev --yarn`
1. Crack open your `package.json` and
   1.  replace `"extends": "react-app"` with `"extends": "sarpik"`
   1.  replace `"eslint": "5.x"` with `"eslint": "6.x"` like so: `yarn add eslint@6.x`, or replace yourself & run `yarn install`
		1. verify that eslint's version is `6.x.y`: run `node node_modules/.bin/eslint --version`
   1.  append `--ext js,jsx,ts,tsx` to `eslint` every time you call it (required for eslint `6.x`, see https://github.com/sarpik/eslint-config-sarpik/issues/4)

Your `package.json` should have this:

```json
{
	"scripts": {
		"lint": "    eslint . --ext js,jsx,ts,tsx",
		"lint:fix": "eslint . --ext js,jsx,ts,tsx --fix"
	},
	"eslintConfig": {
		"extends": "sarpik"
	},
	"devDependencies": {
		"<other-dev-dependency>": "<version>",
		"eslint": "6.x"
	}
}
```

---

Try it out:

```sh
npx create-react-app cra-eslint-ts --template typescript # typescript is optional
cd cra-eslint-ts
```

and then follow the steps above.

Finally, run `yarn lint` and `yarn lint:fix` & verify that `yarn start` still works 🚀

Outcome: https://github.com/sarpik/cra-eslint-ts

**Comment by wesbos** [comment]
thanks :) It works! Adding
