### ISSUE TITLE
Question: Using with Intellij products

### ISSUE THREAD

**Issue by uriklar** [wesbos/eslint-config-wesbos#43]
I'm using VSCode, but several of my teammates use Rubymine and they're having some issues with fixing everything via ESlint. 
Basically, they use a File Watcher to run Eslint, but apparently it's pretty slow there. I'm wondering if anyone here works with this setup but with Intellij. 

Intellij has good prettier support, so we were thinking of leaving prettier as the sole formatter, and then eslint autofix only on a precommit hook. But... my problem is that I *must* have the `react-hooks/exhaustive-deps` eslint rule running with autofix, or else people might have bugs that they won't know about... 

Anyone using Intellij have a good workflow going on here?
Thanks!!

**Comment by eclectic-coding** [comment]
Not sure if you have this fixed yet, but I use Jetbrains IDE's. 

Do not use Filewatcher. 

Go to Settings / Languages & Frameworks / JavaScript / Code Quality / Eslint. 
1. Set to manual eslint configuration
1. Set node interpreter
1. Select eslint package
1. Select configuration file

![Screenshot from 2020-07-01 13-33-30](https://user-images.githubusercontent.com/13651291/86274324-7e37c600-bb9f-11ea-9dd0-4f4721a37673.png)

**Comment by eglove** [comment]
I like to use No Sweat locally. In that case, it's easiest to set ESLint Package to, "Detect package and configuration file from the nearest package.json". It automatically finds the config file from there. But otherwise the same as eclectic-coding's screen above.
