### ISSUE TITLE
Update to VS Code requires a different method to access settings.json

### ISSUE THREAD

**Issue by jamiebergen** [wesbos/eslint-config-wesbos#44]
I noticed with newer versions of VS Code, it's no longer possible to access settings.json via Code/File → Preferences → Settings. There is no {} icon anymore. Instead, I had to go to Workbench → Settings: Editor and switch from ui to json.

This video has good instructions: https://www.youtube.com/watch?v=-wre2TFV4ws

**Comment by MateuszDabrowski** [comment]
Ahoj @jamiebergen,

It is still possible, just the icon has changed from {} to an image of page with an arrow (top right corner): 
![Screenshot 2020-04-15 at 10 51 28](https://user-images.githubusercontent.com/13339456/79318309-17433300-7f07-11ea-9459-b27ee8dcf46c.png)

**Comment by abhijithvijayan** [comment]
`Ctrl + ,`

**Comment by Jiggy-91** [comment]
ah thanks @jamiebergen Jamie!

**Comment by Jiggy-91** [comment]
ahh, this is not working for me like in his 5th video on installing ESLINT :s
