### ISSUE TITLE
Love your config but have a quick question

### ISSUE THREAD

**Issue by jcklpe** [wesbos/eslint-config-wesbos#47]
Love your config! But if I don't want to run your config every single time and then copy paste in my modifications to the eslintrc. 

How would you recommend I go about making my own config? My theory:
**Approach 1**: I fork yours and then add my edits to the .eslint.js file
BUT
How is the eslint.js file different from an eslintrc file? They clearly have different structures to their format.  
**Approach 2:** create my own config and pull in your project as a dep in the same way that you pull in airbnbs. But when I tried `estlint --inti` I didn't really see how I was supposed to include yours as a dep in the way that you included airbnbs. Any suggestions?

Also I like your handy npx install script but not clear how I would modify that part either. I see that install-peer-deps is an npm repo for installing peer deps. That seems self explanatory but how is running that repo to install peer deps different than if I just ran "npm install eslint-config-wesbos"? Why is the "install-peerdeps" thing necessary?

**Comment by MateuszDabrowski** [comment]
Ahoj @jcklpe ,

I would recommend forking his project, applying changes you are interested in (for example to rules in .eslintrc) and then publishing it to your [npm](https://www.npmjs.com) via `npm publish ./`.

This way you will have your version of this in the npm and will be able to use npx install with just small change of path from Wes to your package: 

> npx install-peerdeps yourPackageName@latest --dev

**Comment by jcklpe** [comment]
@MateuszDabrowski excellent! sounds good. I'll do that. 

Any thoughts on why install-peerdeps is used for the npx? I ask more for my own learning and context more than anything.

**Comment by MateuszDabrowski** [comment]
Ahoj @jcklpe,

It's a trick to use install-peerdeps npm package (https://www.npmjs.com/package/install-peerdeps) that is useful for dealing with peer dependencies (https://nodejs.org/es/blog/npm/peer-dependencies/) without actually installing it (by using npx instead of npm).

**Comment by jcklpe** [comment]
@MateuszDabrowski Thanks!
