### ISSUE TITLE
Global Installs with ESLint 7 / couldn't find the config "wesbos" to extend from

### ISSUE THREAD

**Issue by theBhavikJoshi** [wesbos/eslint-config-wesbos#53]
Trying to install but facing this error.

ESLint couldn't find the config "wesbos" to extend from. Please check that the name of the config is correct.
The config "wesbos" was referenced from the config file in "~/.eslintrc".

**Comment by Asjas** [comment]
@theBhavikJoshi Can you try installing the latest version of `eslint-config-wesbos` and see if you get the same error message? 🙂

There was an error being thrown due to an out-of-date package which caused that `failed to find the config "wesbos"` error. I just tested using the latest release of Wes's plugin and it's now fixed.

**Comment by theBhavikJoshi** [comment]
@Asjas thanks for your reply. 
I have tried installing the latest version and still facing the same issue.

**Comment by Asjas** [comment]
Can you post the contents of your `package.json` file here?

**Comment by svikas641** [comment]
I am also facing the same issue 
Failed to load config "wesbos" to extend from. Referenced from: C:\Users\svika\.eslintrc
and all the global files are stored at C:\Users\svika\AppData\Roaming\npm\node_modules
![Screenshot (7)](https://user-images.githubusercontent.com/16942496/91057936-7fd4b600-e645-11ea-8848-2d12d44e27c9.png)

**Comment by theBhavikJoshi** [comment]
@Asjas yes, I am using a node version manager, nvm. Any workaround for this?

**Comment by itstheandre** [comment]
Hey @Asjas is there a way around the nvm issue?

I am also seeing the sam eissue on my computer

**Comment by occam98** [comment]
I'm also seeing the same issue on a global install, even after following the steps to delete everything and try reinstalling.

**Comment by daveholst** [comment]
I'm having the same problem with a global install. I don't believe I have a node version manager installed.

**Comment by svikas641** [comment]
Hi Everyone, who's facing the issue in global installation including me. After a bit of research i found this i don't know how much true this is, if anyone knows please clarify, Thanks.
![Screenshot (9)](https://user-images.githubusercontent.com/16942496/91940270-d2ccfe00-ed14-11ea-9f02-b87a2d3aa78b.png)

**Comment by itstheandre** [comment]
After a lot of research I also found that.  So I guess that Wes's setup wont break amazingly if we dont have an .eslintrc in the root of every project, I guess prettier wont be doing anything, because we disabled everything, right?

**Comment by Asjas** [comment]
I'm not getting the global eslint working and I can get the local installation working immediately. I'd personally suggest setting up this `eslint-config` locally per project, that is how I personally use `eslint`.

For the most part it appears that `eslint` is deprecating the global installation and recommends that `eslint` be installed locally per project. https://github.com/yannickcr/eslint-plugin-react/issues/2339#issuecomment-522645288

People have been recommending to try either `eslint . --resolve-plugins-relative-to="global_node_modules_dir"` in the CLI or to set up `vscode-eslint` with the following settings in the `settings.json` file to resolve the eslint plugins globally but I haven't gotten that working.
```js
"eslint.options": {
  "resolvePluginsRelativeTo": "global_node_modules_dir"
},
```

**Comment by itstheandre** [comment]
I wonder if there is a way to conditionally run the paths. something like: check current folder, check above until it eventually finds the one on the root folder

**Comment by wesbos** [comment]
Shoot eh - I like having an eslint globally because not every .js file I write is a huge project...

**Comment by wesbos** [comment]
I made an issue on the git repo to see if there is a solution for doing something like this.

**Comment by St3f4NS** [comment]
I'm facing this issue on `gatsby new` starter. Working globally with nextjs and everything else, just in gatsby doesnt.

**Comment by wesbos** [comment]
Global installs do not work anymore. Sorry folks!

**Comment by jeremeheh** [comment]
> After a lot of research I also found that. So I guess that Wes's setup wont break amazingly if we dont have an .eslintrc in the root of every project, I guess prettier wont be doing anything, because we disabled everything, right?

Is there any work around on this?

**Comment by Asjas** [comment]
@jeremeheh Can you expand on your question? 🙂

**Comment by SerhatTeker** [comment]
> Global installs do not work anymore. Sorry folks!

I think we should update README according to this then. "No global install anymore"
