### ISSUE TITLE
Question: it works with Gatsby? 

### ISSUE THREAD

**Issue by CuteShaun** [wesbos/eslint-config-wesbos#58]
In my case eslint-config-wesbos does not want works with Gatsby, but it works with CRA.

**Comment by Asjas** [comment]
Hi @CuteShaun 🙂

How are you running `eslint`? As a npm script or on file auto-save?

**Comment by Asjas** [comment]
I just installed a Gatsby Starter and then installed and configured the `eslint-config-wesbos` package. I can get `eslint` to run as a npm script (`npm run lint`) without any issues. 

The only issue I ran into WAAS the auto-fix on save that wouldn't work and that is because the Gatsby Starter had a `.prettierrc` and `.prettierignore` file that was causing a conflict - I removed those two files and the auto-fix on save worked.

The `eslint-config-wesbos` package already includes `prettier` with a prettier config and the external prettier files that the Gatsby starter had was causing a conflict.

**Comment by CuteShaun** [comment]
Hello @Asjas :)

Thank you for responding. I had the same setup, it's `gatsby-starter-blog`. When I'm trying run eslint with `npm run lint` it throw common error: 
<img width="745" alt="Screen Shot 2020-09-04 at 9 51 28 PM" src="https://user-images.githubusercontent.com/28014041/92276292-5fd0ac80-eef9-11ea-8fef-b4b5ef1ff64b.png">


But if I running eslint with autosave, nothing happens :(

What I tried:
- `gatsby clean`, `rm -rf node_modules`, delete .lock files;
- delete prettier, prettier ignore files;
- remove global packages, `npm remove --global eslint-config-wesbos babel-eslint eslint eslint-config-prettier eslint-config-airbnb eslint-plugin-html eslint-plugin-prettier eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react prettier eslint-plugin-react-hooks`;

My .eslintrc:
```
{
  "extends": ["wesbos"],
  "rules": {
    "no-console": 2,
    "prettier/prettier": [
      "error",
      {
        "trailingComma": "es5",
        "singleQuote": true,
        "printWidth": 120,
        "tabWidth": 8
      }
    ]
  }
}
```

My VScode settings:
<img width="547" alt="Screen Shot 2020-09-04 at 10 03 52 PM" src="https://user-images.githubusercontent.com/28014041/92276939-a07cf580-eefa-11ea-9d08-c8b08e4a7799.png">


Global .eslintrc config:
<img width="182" alt="Screen Shot 2020-09-04 at 10 09 25 PM" src="https://user-images.githubusercontent.com/28014041/92277306-50526300-eefb-11ea-93fd-85b607151203.png">

Dev dep. from package.json:
`"devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-wesbos": "0.0.22",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-html": "^6.0.3",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^1.7.0",
    "prettier": "^1.19.1"
  },`

I would be grateful for any idea why this might be happening?

**Comment by CuteShaun** [comment]
Reinstall ESLint plugin for VSCode was helpful for me, 
now everything works, Hurray! 😊

**Comment by Asjas** [comment]
Glad you got it working 🙂
