### ISSUE TITLE
eslint conflict when implementing this in create react app

### ISSUE THREAD

**Issue by svikas641** [wesbos/eslint-config-wesbos#64]
react scripts uses eslint@6.6.0 but we are using eslint7 something, so react script preventing us to do that it also showing this
`
Manually installing incompatible versions is known to cause hard-to-debug issues.
If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.
`
the way i got rid from this is by installing the eslint@6.6.0 . Should we mention this in installation guide ?

**Comment by Digital-Coder** [comment]
is there another way to solve it instead of manually installing eslint@6.6.0 ? It should not ask it if I change eslintConfig to "wesbos" in package.json instead of default "react-app".

**Comment by taniket15** [comment]
`create-react-app` has release `v4` which adds support for eslint +7.

**Comment by wesbos** [comment]
wahoo! Gonna close this then :)
