### ISSUE TITLE
Create React App requires Eslint v7.11.0 

### ISSUE THREAD

**Issue by keremcanb** [wesbos/eslint-config-wesbos#71]
Wesbos installs Eslint v7.8.1, but application does not start with this error:
"The react-scripts package provided by Create React App requires a dependency: "eslint": "^7.11.0". "

**Comment by Dujota** [comment]
@keremcanb what error are you getting? you most likely need a .env with the `SKIP_PREFLIGHT=true`

**Comment by IsraelChidera** [comment]
I am having the same issue and I want to use ESLINT for linting. Adding SKIP_PREFLIGHT_CHECK=true will disable linting and I do not want to disable ESLINT. Please I need a solution
