### ISSUE TITLE
Can't install ESlint and Prittier dependencies?

### ISSUE THREAD

**Issue by valeriirivne** [wesbos/eslint-config-wesbos#76]
Hey, I have a a package.json file, created one with npm init. But I failed to install everything needed by the config: npx install-peerdeps --dev eslint-config-wesbos. What am I doing wrong? Thank you. 
![NPM ERR1](https://user-images.githubusercontent.com/75642477/107756163-80185900-6d2c-11eb-882d-a49152663e01.png)

**Comment by Asjas** [comment]
Hey, what version of Node.js and `npm` are you using? 🙂

**Comment by valeriirivne** [comment]
![version node](https://user-images.githubusercontent.com/75642477/107765218-1901a100-6d3a-11eb-88da-ad42b7e4605f.png)

**Comment by amazingrando** [comment]
I also ran into this issue on node 15. Using v14 and everything worked.

**Comment by Fran2304** [comment]
> Hey,
> ![version node](https://user-images.githubusercontent.com/75642477/107765218-1901a100-6d3a-11eb-88da-ad42b7e4605f.png)

**Comment by Fran2304** [comment]
I had run `npx install-peerdeps@v2.0.2 --dev eslint-config-wesbos `
 version but I had the same problem 😢

**Comment by raleigh9123** [comment]
Also not able to install via terminal 😞

I only realized my prettier wasn't working as I was playing with a new project. Then learned that prettier globals don't work?? So I needed to reinstall the wesbos stuff and now I'm wondering what I need per project if I'm going to just setup each one individually.

**Comment by Asjas** [comment]
Since global ESLint configs no longer work you can follow the guide that Wes created for Per Project installations.

https://github.com/wesbos/eslint-config-wesbos#local--per-project-install

**Comment by BrendyRyan** [comment]
I ended up installing `npm@6.14.0` and it worked for me. 
I probably could try a more recent version but I tried `@7.13.0` and it didn't work so i went back to one I knew would.
