### ISSUE TITLE
Failed to load config "wesbos" to extend from. Referenced from: C:\Users\user\.eslintrc

### ISSUE THREAD

**Issue by emred2700** [wesbos/eslint-config-wesbos#81]
Hi, I get this error when I try to use ESLint. I did everything as stated and all my dependencies etc are updated.  I am trying to use a global setup and I am on a Windows system. 

Steps to produce:
1. use npx for global install, set vscode settings. And this is the response in the output console.

**Comment by Asjas** [comment]
Global installs are not supported by ESLint anymore - that is the cause of your issue. 🙂

You need to do the `per project/local` installation.

**Comment by Akshay-akkay** [comment]
Really, WHY???? 😭

**Comment by Asjas** [comment]
They removed that functionality back in ESLint 6 🙂

**Comment by Dujota** [comment]
I had this issue as well on a windows machine my work provided, you will need to install it at the `c:\\users\user\`  directory 

so run `npx install-peerdeps eslint-config-wesbos`  in the the  same directory as the eslitrc file and then restart your vscode or whatever it will now be picked up 

*** note *** if you get a failed to install npx error .. you may need to downgrade your node js version down to LTS
