### ISSUE TITLE
Issue on using top level await in node files

### ISSUE THREAD

**Issue by akshaymattoo** [wesbos/eslint-config-wesbos#91]
116:19  error  Parsing error: Unexpected reserved word 'await'.
const dbClient = await new DBConnect().connect()

**Comment by Dujota** [comment]
without seeing your code, its hard to help you, but usually its because you don't have async on the function that dbClient variable to scoped to. 

this will helo you out https://stackoverflow.com/questions/42299594/await-is-a-reserved-word-error-inside-async-function
