### ISSUE TITLE
2.0 Beta Testing 

### ISSUE THREAD

**Issue by wesbos** [wesbos/eslint-config-wesbos#97]
If anyone wants to test the latest version of this eslint on your project, please do!  

There aren't many rule changes, but it's all updated for the latest packages and has support for typescript.

1. In your project run `npx install-peerdeps --dev eslint-config-wesbos@2.0.0-beta.11` 
2. In yout `.eslintrc` file, use `{ extends: "wesbos" }` for JS, or `{ extends: "wesbos/typescript" }` for TS
3.  For JS, you might need a `.babelrc` file with `{}` in it, let me know if you do

Let me know if there are any issues. Would like to get this sucker shipped as the current one is clashing with a few libs.

**Comment by islami00** [comment]
Currently testing beta11
It works! my editor lit up right after the install and `extends:"wesbos"`
Now trying to get it to play nice with prettier extension

**Comment by wesbos** [comment]
@islami00 thanks, you shouldn't have to install eslint-prettier. Will have a look into it! Will also check those rules

**Comment by GPorter43** [comment]
Using Windows 10 and had to have a Babelrc file with empty brackets for js files. let me know if you need anything to debug

**Comment by wesbos** [comment]
Thanks! I'm just looking and I thinkI can avoid that with requireConfigFile. Will try it

https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#additional-parser-configuration

**Comment by wesbos** [comment]
Yep that did it! No need for the empty babel file now. Thanks again

**Comment by wesbos** [comment]
2.0.0 is out! Let me knwo if you hit anything else!
